pluginName=Gettw Plugin
providerName=Sample Plugin Provider, Inc

editorName=Gettw Diagram Editing
context.description=Gettw Diagram Editing
context.name=In Gettw Diagram Editor
newWizardName=Gettw Diagram
newWizardDesc=Creates Gettw diagram.

initDiagramActionLabel=Initialize gettw_diagram diagram file


navigatorContentName=*.gettw_diagram diagram contents
domainNavigatorContentName=*.gettw model contents
update.diagram.name=Update Gettw diagram
update.diagram.description=Perform Gettw diagram update


# Property Sheet
tab.appearance=Appearance
tab.diagram=Rulers & Grid
tab.domain=Core

# Preferences
prefpage.gettw.diagram.general=Gettw Diagram
prefpage.gettw.diagram.appearance=Appearance
prefpage.gettw.diagram.connections=Connections
prefpage.gettw.diagram.printing=Printing
prefpage.gettw.diagram.rulersAndGrid=Rulers And Grid


# Providers
metatype.name.GETTWDiagram_1000=Undefined
metatype.name.Superscript_2001=Superscript
metatype.name.Subscript_2002=Subscript
metatype.name.TextIndex_2003=TextIndex
metatype.name.Rectangle_2004=Rectangle
metatype.name.RoundedRectangle_2005=RoundedRectangle
metatype.name.Ellipse_2006=Ellipse
metatype.name.Triangle_2007=Triangle
metatype.name.Diamond_2008=Diamond
metatype.name.TriangleDown_2009=TriangleDown
metatype.name.TriangleLeft_2010=TriangleLeft
metatype.name.TriangleRight_2011=TriangleRight
metatype.name.Actor_2012=Actor
metatype.name.Package_2013=Package
metatype.name.CustomLink_2014=CustomLink
metatype.name.Text_2015=Text
metatype.name.Picture_2016=Picture
metatype.name.CustomShape_2017=CustomShape

# Commands and menu actions
cmdcategory.name=Gettw Editor Commands
cmdcategory.desc=Gettw Editor Commands

