pluginName=Mof Plugin
providerName=Sample Plugin Provider, Inc

editorName=Mof Diagram Editing
context.description=Mof Diagram Editing
context.name=In Mof Diagram Editor
newWizardName=Mof Diagram
newWizardDesc=Creates Mof diagram.

initDiagramActionLabel=Initialize mof_diagram diagram file


navigatorContentName=*.mof_diagram diagram contents
domainNavigatorContentName=*.mof model contents
update.diagram.name=Update Mof diagram
update.diagram.description=Perform Mof diagram update


# Property Sheet
tab.appearance=Appearance
tab.diagram=Rulers & Grid
tab.domain=Core

# Preferences
prefpage.tfg.diagram.general=Mof Diagram
prefpage.tfg.diagram.appearance=Appearance
prefpage.tfg.diagram.connections=Connections
prefpage.tfg.diagram.printing=Printing
prefpage.tfg.diagram.rulersAndGrid=Rulers And Grid


# Providers
metatype.name.UMLDiagram_1000=Undefined
metatype.name.Clas_2001=Clas
metatype.name.Generalization_4001=Generalization

# Commands and menu actions
cmdcategory.name=Mof Editor Commands
cmdcategory.desc=Mof Editor Commands

