pluginName=Components Plugin
providerName=Sample Plugin Provider, Inc

editorName=Components Diagram Editing
context.description=Components Diagram Editing
context.name=In Components Diagram Editor
newWizardName=Components Diagram
newWizardDesc=Creates Components diagram.

initDiagramActionLabel=Initialize components_diagram diagram file


navigatorContentName=*.components_diagram diagram contents
domainNavigatorContentName=*.components model contents
update.diagram.name=Update Components diagram
update.diagram.description=Perform Components diagram update


# Property Sheet
tab.appearance=Appearance
tab.diagram=Rulers & Grid
tab.domain=Core

# Preferences
prefpage.tfg.diagram.general=Components Diagram
prefpage.tfg.diagram.appearance=Appearance
prefpage.tfg.diagram.connections=Connections
prefpage.tfg.diagram.printing=Printing
prefpage.tfg.diagram.rulersAndGrid=Rulers And Grid


# Providers
metatype.name.UMLDiagram_1000=Undefined
metatype.name.Package_2001=Package
metatype.name.Clas_2002=Clas
metatype.name.Interface_2003=Interface
metatype.name.Enumeration_2004=Enumeration
metatype.name.Note_2005=Note
metatype.name.Package_3001=Package
metatype.name.Clas_3002=Clas
metatype.name.Property_3003=Property
metatype.name.Method_3004=Method
metatype.name.Parameter_3005=Parameter
metatype.name.Interface_3006=Interface
metatype.name.Method_3007=Method
metatype.name.Enumeration_3008=Enumeration
metatype.name.EnumLiteral_3009=EnumLiteral
metatype.name.Generalization_4001=Generalization
metatype.name.Implementation_4002=Implementation
metatype.name.Association_4003=Association
metatype.name.Aggregation_4004=Aggregation
metatype.name.Composition_4005=Composition
metatype.name.Dependency_4006=Dependency
metatype.name.NoteLink_4007=NoteLink

# Commands and menu actions
cmdcategory.name=Components Editor Commands
cmdcategory.desc=Components Editor Commands

