#

pluginName = Mof Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_UMLDiagram_type = UML Diagram
_UI_Nodo_type = Nodo
_UI_NodoUno_type = Nodo Uno
_UI_NodoDos_type = Nodo Dos
_UI_Enlace_type = Enlace
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_UMLDiagram_nodos_feature = Nodos
_UI_UMLDiagram_enlaces_feature = Enlaces
_UI_Nodo_nombre_feature = Nombre
_UI_Nodo_color_feature = Color
_UI_Nodo_colorBorde_feature = Color Borde
_UI_NodoUno_nodosDos_feature = Nodos Dos
_UI_NodoDos_forma_feature = Forma
_UI_NodoDos_linea_feature = Linea
_UI_Enlace_texto_feature = Texto
_UI_Enlace_origen_feature = Origen
_UI_Enlace_destino_feature = Destino
_UI_Enlace_linea_feature = Linea
_UI_Enlace_textoExtremoOrigen_feature = Texto Extremo Origen
_UI_Enlace_textoExtremoDestino_feature = Texto Extremo Destino
_UI_Enlace_formaExtremoOrigen_feature = Forma Extremo Origen
_UI_Enlace_formaExtremoDestino_feature = Forma Extremo Destino
_UI_Enlace_color_feature = Color
_UI_Unknown_feature = Unspecified

_UI_Color_Blanco_literal = Blanco
_UI_Color_Negro_literal = Negro
_UI_Color_Rojo_literal = Rojo
_UI_Color_Verde_literal = Verde
_UI_Color_Amarillo_literal = Amarillo
_UI_Color_Azul_literal = Azul
_UI_Color_Rosa_literal = Rosa
_UI_Color_Lila_literal = Lila
_UI_Color_Naranja_literal = Naranja
_UI_Forma_Rectangulo_literal = Rectangulo
_UI_Forma_RectanguloRedondeado_literal = RectanguloRedondeado
_UI_Forma_Circulo_literal = Circulo
_UI_Forma_CirculoDoble_literal = CirculoDoble
_UI_Forma_Barra_literal = Barra
_UI_Forma_Rombo_literal = Rombo
_UI_Forma_Actor_literal = Actor
_UI_Linea_Continua_literal = Continua
_UI_Linea_Discontinua_literal = Discontinua
_UI_Visibilidad_Privado_literal = Privado
_UI_Visibilidad_Publico_literal = Publico
_UI_Visibilidad_Protegido_literal = Protegido
_UI_Visibilidad_Paquete_literal = Paquete
_UI_Visibilidad_Estático_literal = Estático
_UI_FormaExtremoOrigen_Ninguna_literal = Ninguna
_UI_FormaExtremoOrigen_FlechaAbierta_literal = FlechaAbierta
_UI_FormaExtremoOrigen_FlechaCerrada_literal = FlechaCerrada
_UI_FormaExtremoDestino_Ninguna_literal = Ninguna
_UI_FormaExtremoDestino_RomboSinRelleno_literal = RomboSinRelleno
_UI_FormaExtremoDestino_RomboRelleno_literal = RomboRelleno
