<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mof" nsURI="mof" nsPrefix="mof">
  <eClassifiers xsi:type="ecore:EClass" name="UMLDiagram">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Nodeone" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Relationship" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Color">
    <eLiterals name="Blanco"/>
    <eLiterals name="Negro" value="1"/>
    <eLiterals name="Azul" value="2"/>
    <eLiterals name="Amarillo" value="3"/>
    <eLiterals name="Naranja" value="4"/>
    <eLiterals name="Rojo" value="5"/>
    <eLiterals name="Verde" value="6"/>
    <eLiterals name="Rosa" value="7"/>
    <eLiterals name="Lila" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Nodeone" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clas" eSuperTypes="#//Nodeone">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//Color"
        defaultValueLiteral="Blanco"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="colorborde" eType="#//Color"
        defaultValueLiteral="Blanco"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Nodeone"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Nodeone"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Generalization" eSuperTypes="#//Relationship">
    <eAnnotations source="gmf.link">
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="target.decoration" value="closedarrow"/>
      <details key="style" value="solid"/>
      <details key="tool.name" value="Generatization"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
