<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mof" nsURI="mof" nsPrefix="mof">
  <eClassifiers xsi:type="ecore:EClass" name="UMLDiagram">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodos" upperBound="-1"
        eType="#//Nodo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enlaces" upperBound="-1"
        eType="#//Enlace" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Color">
    <eLiterals name="Blanco"/>
    <eLiterals name="Negro" value="1"/>
    <eLiterals name="Rojo" value="2"/>
    <eLiterals name="Verde" value="3"/>
    <eLiterals name="Amarillo" value="4"/>
    <eLiterals name="Azul" value="5"/>
    <eLiterals name="Rosa" value="6"/>
    <eLiterals name="Lila" value="7"/>
    <eLiterals name="Naranja" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Nodo">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//Color"
        defaultValueLiteral="Blanco"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descripcion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enlace">
    <eAnnotations source="gmf.link">
      <details key="source" value="origen"/>
      <details key="target" value="destino"/>
      <details key="style" value="solid"/>
      <details key="target.decoration" value="arrow"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origen" lowerBound="1"
        eType="#//Nodo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destino" lowerBound="1"
        eType="#//Nodo"/>
  </eClassifiers>
</ecore:EPackage>
